spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:koko_chat}?connectionTimeZone=UTC&forceConnectionTimeZoneToSession=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:koko}
    password: ${MYSQL_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 0
      connection-timeout: 3000
  flyway:
    enabled: true
    locations: classpath:db/migration
    fail-on-missing-locations: true
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      connect-timeout: 3s
      timeout: 3s
  rabbitmq:
    host: ${RABBITMQ_HOST:127.0.0.1}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:koko}
    password: ${RABBITMQ_PASSWORD}
    connection-timeout: 5s
    publisher-confirm-type: correlated
    publisher-returns: true
    dynamic: false
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 5
